# Generated by Django 3.2 on 2021-05-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedorder',
            name='total_weight_of_order',
            field=models.IntegerField(default=0),
        ),
    ]
