# Generated by Django 3.2 on 2021-05-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_assignedorder_total_weight_of_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedorder',
            name='order_assigned_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
