# Generated by Django 3.2 on 2021-05-02 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_assignedorder_order_assigned_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedorder',
            name='order_assigned_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 22, 58, 56, 594961)),
        ),
    ]
