# Generated by Django 3.2 on 2021-05-02 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_assignedorder_order_assigned_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedorder',
            name='order_assigned_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 3, 0, 24, 32, 654783)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 3, 0, 24, 32, 654346)),
        ),
    ]
